name: Fetch GitHub Data

on:
  schedule:
    # Runs at 12 AM UTC every day (0 0 * * *)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger as well

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies from requirements.txt (if exists)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run your Python script to fetch data
      - name: Run fetch_github_data.py
        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python fetch_simple_data.py
